---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airflow-base
  namespace: airflow
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: f222cf2e-9059-4809-9567-5c02ce6d0163
      resourcegroup: osdu-self-cplbjhha-yaom-rg
      identity: osdu-self-cplbjhha-yaom-osdu-identity
      identity_id: d366f9eb-b848-4ac0-a70e-bde113db09b2
      keyvault: osdu-self-cplbjh-yaom-kv
      appid: 0fcf2808-d6b3-4569-a2db-61f4a083741d
    image:
      repository: osduselfcplbjhyaomcr.azurecr.io
